services:
  # MySQL Database
  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: CruciWeb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8889:3306"
    volumes:
      - cruciweb_mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  cruciweb_mysql_data:

networks:
  app-network:
    driver: bridge
